spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: turma926
    hikari:
      keepaliveTime: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000